### ISSUE TITLE
TS2507: Type 'any' is not a constructor function type.

### ISSUE THREAD

**Issue by vineethk1984** [Hipparch/Angular2-navigate-with-data#1]
Hello, when trying to extend ROUTER, I am getting above error.
Line:  export class Router extends ReflectRouter.ROUTER() {...}
Can you please help me with understanding what could be the problem?

**Comment by Hipparch** [comment]
Which version of the Typescript do you use?

**Comment by Hipparch** [comment]
Please, try again.
